group: greek_protipa_exams_closed_aggregate_private
task:
  - greek_protipa_exams_language_closed_private
  - greek_protipa_exams_maths_closed_private
  - greek_protipa_exams_religious_studies_closed_private
aggregate_metric_list:
  - metric: exact_match
    aggregation: mean
